### PR TITLE
Make it possible to run bananalyzer server using Docker

### PR DESCRIPTION
**Pull request by snshn**
Enables `make` commands and makes it possible to run and develop using Docker

### CODE REVIEW

**Review by asim-shrestha — APPROVED** [review]

**Comment by snshn** [comment]
All tests pass, but I had to cheat in a couple of spots.

Here's why: recursion.  I tried using `Iterable[["AllowedJSON"]` but the world is not ready yet, maybe Python 3.12 supports it, maybe it's just the wrong way to do it.

The main issue is that schemas are recursive (as I remember from implementing that part for Harambe).  I'm not familiar enough with bananacrate, so please take a peek and let me know what we can and cannot change to make tests pass;  we can always avoid recursion and have additional methods for filtering and formatting results, but then nested arrays and objects won't be supported.

**Review by awtkns — APPROVED** [review]

**Comment by awtkns** [comment]
@snshn is this good to merge now?

**Comment by snshn** [comment]
@awtkns this should be good, it's passing all the tests, I only worry about https://github.com/reworkd/bananalyzer/pull/87/files#diff-c9d7dc2b19a07bc9d6d674f369754102e904ce405c6261543976430a640db6cbR8 and https://github.com/reworkd/bananalyzer/pull/87/files#diff-222a72beb539b057695aadbedc01313c2d8ba03852fd18e595655df5c0f3f1e2R8 — it may affect what happens outside, on your platform, since the schemas are changed, and now support nulls and recursion where they didn't before

**Comment by snshn** [comment]
I can go ahead and merge it in if the modified schemas isn't a problem.  I think we can add recursion and deal with nulls later, as long as it doesn't break anything in your live environment.

**Pull request merged**
